### ISSUE TITLE
 The contract verification failed.

### ISSUE THREAD

**Issue by Pitfall-cmd** [PatrickAlphaC/hardhat-fund-me-fcc#115]
Hi, I got some problem when I deployed for verification ...
```shell
 yarn hardhat deploy --network goerli --tags fundme
yarn run v1.22.19
warning ../package.json: No license field
$ /workspace/gitpod/3hardhat-fund-me/node_modules/.bin/hardhat deploy --network goerli --tags fundme
Nothing to compile
----------------------------------------------------
Deploying FundMe and waiting for confirmations...
reusing "FundMe" at 0x2c9ddb25133ea623333ccf6cea0d92e02916e82d
FundMe deployed at 0x2c9ddb25133ea623333ccf6cea0d92e02916e82d
Verifying contract...
Nothing to compile
Successfully submitted source code for contract
contracts/FundMe.sol:FundMe at 0x2c9ddb25133ea623333ccf6cea0d92e02916e82d
for verification on the block explorer. Waiting for verification result...

We tried verifying your contract FundMe without including any unrelated one, but it failed.
Trying again with the full solc input used to compile and deploy it.
This means that unrelated contracts may be displayed on Etherscan...

Successfully submitted source code for contract
contracts/FundMe.sol:FundMe at 0x2c9ddb25133ea623333ccf6cea0d92e02916e82d
for verification on the block explorer. Waiting for verification result...

NomicLabsHardhatPluginError: The contract verification failed.
Reason: Fail - Unable to verify
    at SimpleTaskDefinition.verifySubtask [as action] (/workspace/gitpod/3hardhat-fund-me/node_modules/@nomiclabs/hardhat-etherscan/src/index.ts:350:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Environment._runTaskDefinition (/workspace/gitpod/3hardhat-fund-me/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at Environment.run (/workspace/gitpod/3hardhat-fund-me/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at verify (/workspace/gitpod/3hardhat-fund-me/utils/verify.js:6:9)
    at Object.module.exports [as func] (/workspace/gitpod/3hardhat-fund-me/deploy/01-deploy-fund-me.js:33:9)
    at DeploymentsManager.executeDeployScripts (/workspace/gitpod/3hardhat-fund-me/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1219:22)
    at DeploymentsManager.runDeploy (/workspace/gitpod/3hardhat-fund-me/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1052:5)
    at SimpleTaskDefinition.action (/workspace/gitpod/3hardhat-fund-me/node_modules/hardhat-deploy/src/index.ts:438:5)
    at Environment._runTaskDefinition (/workspace/gitpod/3hardhat-fund-me/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
Done in 11.14s.
```

**Comment by mishkatmustafid** [comment]
I have the same issue. No answers found yet.

**Comment by Dynamitetechdev** [comment]
You can’t Verify without Etherscan API key, Check if it is inputted correctly
