### ISSUE TITLE
ERROR in DEPLOYMENT

### ISSUE THREAD

**Issue by thakuradi** [PatrickAlphaC/hardhat-fund-me-fcc#162]
![Screenshot (54)](https://github.com/PatrickAlphaC/hardhat-fund-me-fcc/assets/84377163/5dbb6548-3f53-4b8b-aacc-2a145e47c17e)
When i deploy my script ... in 01 
it's showing there is not an  artifact of Fund me but there is already an artifact. and like I also delete the artifact and here is the error.
yarn hardhat deploy 
yarn run v1.22.15
warning package.json: No license field
$ hardhat deploy
Compiled 8 Solidity files successfully
hi
Local network detected! Deploying mocks...
deploying "MockV3Aggregator" (tx: 0x7e29e8ee3c67b18648f3fe15adcc0ea408e835cac0fee09a37c8a5c296b9ec68)...: deployed at 0x5FbDB2315678afecb367f032d93F642f64180aa3 with 569759 gas
Mocks deployed !
-------------------------------------------------------
An unexpected error occurred:

Error: ERROR processing /home/thakuradi/hardhat-fund-me-fcc/deploy/01-deploy-fund-me.js:
Error: cannot find artifact "Fundme"
    at getArtifact (/home/thakuradi/hardhat-fund-me-fcc/node_modules/hardhat-deploy/src/DeploymentsManager.ts:207:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
    at getArtifactFromOptions (/home/thakuradi/hardhat-fund-me-fcc/node_modules/hardhat-deploy/src/helpers.ts:527:18)
    at getLinkedArtifact (/home/thakuradi/hardhat-fund-me-fcc/node_modules/hardhat-deploy/src/helpers.ts:537:38)
    at _deploy (/home/thakuradi/hardhat-fund-me-fcc/node_modules/hardhat-deploy/src/helpers.ts:558:54)
    at _deployOne (/home/thakuradi/hardhat-fund-me-fcc/node_modules/hardhat-deploy/src/helpers.ts:1026:16)
    at Object.module.exports [as func] (/home/thakuradi/hardhat-fund-me-fcc/deploy/01-deploy-fund-me.js:23:20)
    at DeploymentsManager.executeDeployScripts (/home/thakuradi/hardhat-fund-me-fcc/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1225:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
    at DeploymentsManager.runDeploy (/home/thakuradi/hardhat-fund-me-fcc/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1055:5)
    at SimpleTaskDefinition.action (/home/thakuradi/hardhat-fund-me-fcc/node_modules/hardhat-deploy/src/index.ts:438:5)
    at Environment._runTaskDefinition (/home/thakuradi/hardhat-fund-me-fcc/node_modules/hardhat/src/internal/core/runtime-environment.ts:330:14)
    at Environment.run (/home/thakuradi/hardhat-fund-me-fcc/node_modules/hardhat/src/internal/core/runtime-environment.ts:163:14)
    at SimpleTaskDefinition.action (/home/thakuradi/hardhat-fund-me-fcc/node_modules/hardhat-deploy/src/index.ts:584:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

video at 10:51:36

**Comment by Astrofox1** [comment]
make sure it's spelled correctly!

**Comment by thakuradi** [comment]
> make sure it's spelled correctly!

bro I checked everything it's correct I don't know where is the problem....:(

**Comment by Astrofox1** [comment]
Fundme is not FundMe you know ^^
try renaming everything in your code from Fundme to FundMe as well as your contract's name!

**Comment by thakuradi** [comment]
> Fundme is not FundMe you know ^^ try renaming everything in your code from Fundme to FundMe as well as your contract's name!

thanks bro problem solved , I will hug you right now

**Comment by Astrofox1** [comment]
You're welcome mate!
