### ISSUE TITLE
NomicLabsHardhatPluginError: Unsupported network ("sepolia", chainId: 11155111).

### ISSUE THREAD

**Issue by Arveymenon** [PatrickAlphaC/hardhat-fund-me-fcc#165]
```
NomicLabsHardhatPluginError: Unsupported network ("sepolia", chainId: 11155111).
    at getEtherscanEndpoints (/Users/arulvinayak/Desktop/Projects/web3/hardhat-fund-me-fcc/node_modules/@nomiclabs/hardhat-etherscan/src/network/prober.ts:34:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Environment._runTaskDefinition (/Users/arulvinayak/Desktop/Projects/web3/hardhat-fund-me-fcc/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/Users/arulvinayak/Desktop/Projects/web3/hardhat-fund-me-fcc/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at SimpleTaskDefinition.verifySubtask [as action] (/Users/arulvinayak/Desktop/Projects/web3/hardhat-fund-me-fcc/node_modules/@nomiclabs/hardhat-etherscan/src/index.ts:191:30)
    at Environment._runTaskDefinition (/Users/arulvinayak/Desktop/Projects/web3/hardhat-fund-me-fcc/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/Users/arulvinayak/Desktop/Projects/web3/hardhat-fund-me-fcc/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at verify (/Users/arulvinayak/Desktop/Projects/web3/hardhat-fund-me-fcc/utils/verify.js:6:5)
    at Object.module.exports [as func] (/Users/arulvinayak/Desktop/Projects/web3/hardhat-fund-me-fcc/deploy/99-deploy-storage-fun.js:20:9)
    at DeploymentsManager.executeDeployScripts (/Users/arulvinayak/Desktop/Projects/web3/hardhat-fund-me-fcc/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1220:22)
```

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
