### ISSUE TITLE
Can't deploy mockV3Aggregator

### ISSUE THREAD

**Issue by Dervoo** [PatrickAlphaC/hardhat-fund-me-fcc#25]
Hello i have problems with: 01-deploy-fund me (npx hardhat deploy --tags fundme)

Error: ERROR processing /Users/dervoo/Kontrakty/deploy/01-deploy-FundMe.js:
Error: No deployment found for: MockV3Aggregator
    at Object.get (/Users/dervoo/Kontrakty/node_modules/hardhat-deploy/src/DeploymentsManager.ts:162:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.module.exports [as func] (/Users/dervoo/Kontrakty/deploy/01-deploy-FundMe.js:12:34)
    at DeploymentsManager.executeDeployScripts (/Users/dervoo/Kontrakty/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1219:22)
    at DeploymentsManager.runDeploy (/Users/dervoo/Kontrakty/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1052:5)
    at SimpleTaskDefinition.action (/Users/dervoo/Kontrakty/node_modules/hardhat-deploy/src/index.ts:438:5)
    at Environment._runTaskDefinition (/Users/dervoo/Kontrakty/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at Environment.run (/Users/dervoo/Kontrakty/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)

```
const { networkConfig } = require("../helper-hardhat-config")
const { network } = require("hardhat")
const { verify } = require("../utils/verify")
const { developmentChains } = require("../helper-hardhat-config")

module.exports = async ({ getNamedAccounts, deployments }) => {
    const { deploy, log } = deployments
    const { deployer } = await getNamedAccounts()
    const chainId = network.config.chainId

    // const ethUsdPriceFeedAddress = networkConfig[chainId]["ethUsdPriceFeed"]
    let ethUsdPriceFeedAddress
    if(developmentChains.includes(network.name)) {
        const ethUsdAggregator = await deployments.get("MockV3Aggregator")
        ethUsdPriceFeedAddress = ethUsdAggregator.address
    } else {
        ethUsdPriceFeedAddress = networkConfig[chainId]["ethUsdPriceFeed"]
    }
    const args = [ethUsdPriceFeedAddress]
    const fundMe = await deploy("FundMe", {
        from: deployer,
        args: [ethUsdPriceFeedAddress],
        log: true,
        waitConfirmations: network.config.blockConfirmations || 1,
    })
    if(!developmentChains.includes(network.name) && process.env.ETHERSCAN_API_KEY) {
        await verify(fundMe.address, args)
    }
}
module.exports.tags = ["all", "fundme"]
```

following by error in test: 
```
ERROR processing /Users/dervoo/Kontrakty/deploy/01-deploy-FundMe.js:
Error: No deployment found for: mockV3Aggregator
    at Object.get (/Users/dervoo/Kontrakty/node_modules/hardhat-deploy/src/DeploymentsManager.ts:162:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.module.exports [as func] (/Users/dervoo/Kontrakty/deploy/01-deploy-FundMe.js:15:34)
    at DeploymentsManager.executeDeployScripts (/Users/dervoo/Kontrakty/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1219:22)
    at DeploymentsManager.runDeploy (/Users/dervoo/Kontrakty/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1052:5)
    at Object.fixture (/Users/dervoo/Kontrakty/node_modules/hardhat-deploy/src/DeploymentsManager.ts:315:9)
    at Context.<anonymous> (/Users/dervoo/Kontrakty/test/staging/unit/FundMe.test.js:17:9)
```
AND while trying to deploy:

```
Error: ERROR processing /Users/dervoo/Kontrakty/deploy/01-deploy-FundMe.js:
TypeError: Cannot read properties of undefined (reading 'length')
```

**Comment by jorgelannister** [comment]
If you run with the tag --fundme, it will no run the 00-deploy-mocks.js on your local network. 
This will only work deploying in a testnet

**Comment by HuesoSkywalker** [comment]
i am having the same ERROR

```
Error: ERROR processing /Users/dervoo/Kontrakty/deploy/01-deploy-FundMe.js:
TypeError: Cannot read properties of undefined (reading 'length')
```

**Comment by HuesoSkywalker** [comment]
Hello,

I am having the same error when running --tags mocks

```Error: ERROR processing /home/huesoskywalker/web3/hardhat-fund-me/deploy/00-deploy-mocks.js:
TypeError: Cannot read properties of undefined (reading 'length')
```

```
Error: ERROR processing /Users/dervoo/Kontrakty/deploy/01-deploy-FundMe.js:
TypeError: Cannot read properties of undefined (reading 'length')

**Comment by HuesoSkywalker** [comment]
Hello, 
          I am having a similar issue while running deploying --tags mocks

```
Error: ERROR processing /home/huesoskywalker/web3/hardhat-fund-me/deploy/00-deploy-mocks.js:
TypeError: Cannot read properties of undefined (reading 'length')
```

**Comment by jawadgit** [comment]
Hi Dervoo

I am still stuck in  this issue. 

I am running following command

`yarn hardhat deploy`

still getting same above error.

please clearly specify where i can change the network 

thanks in advance

waiting for your reply

**Comment by Dervoo** [comment]
In my situation it was only typo for network.name, I would suggest you to check it again at least few times, I checked my code few times and found this type simply as that ; p

**Comment by Dervoo** [comment]
Also this one works for me: 

`const { networkConfig, developmentChains } = require("../helper-hardhat-config")
const { network } = require("hardhat")
const { verify } = require("../utils/verify")
// const { helperConfig } = require("../helper-hardhat-config")
// const networkConfig = helperConfig.networkConfig

module.exports = async ({ getNamedAccounts, deployments }) => {
    const { deploy, log } = deployments
    const { deployer } = await getNamedAccounts()
    const chainId = network.config.chainId

    // const ethUsdPriceFeedAddress = networkConfig[chainId]["ethUsdPriceFeed"]
    let ethUsdPriceFeedAddress
    if (developmentChains.includes(network.name)) {
        const ethUsdAggregator = await deployments.get("MockV3Aggregator")
        ethUsdPriceFeedAddress = ethUsdAggregator.address
    } else {
        ethUsdPriceFeedAddress = networkConfig[chainId]["ethUsdPriceFeed"]
    }
    const args = [ethUsdPriceFeedAddress]
    const fundMe = await deploy("FundMe", {
        from: deployer,
        args: [ethUsdPriceFeedAddress],
        log: true,
        waitConfirmations: network.config.blockConfirmations || 1,
    })
    if (
        !developmentChains.includes(network.name) &&
        process.env.ETHERSCAN_API_KEY
    ) {
        await verify(fundMe.address, args)
    }
    log("__________________________________")
}
module.exports.tags = ["all", "fundme"]

// npx hardhat node -> z tymi ustawieniami pozwoli nam na zdeployowanie kontraktu i mocka lokalnie i tez odpalenia kont
`

**Comment by jawadgit** [comment]
Hi @Dervoo 

I am still stuck . I used your code but still same error

I am attaching following code in deploy-fundme.js 

`
const { networkConfig, developmentChains } = require("../helper-hardhat-config")
const { network } = require("hardhat")
const { verify } = require("../utils/verify")

module.exports = async ({ getNamedAccounts, deployments }) => {
    const { deploy, log } = deployments
    const { deployer } = await getNamedAccounts()
    const chainId = network.config.chainId

    let ethUsdPriceFeedAddress
    if (developmentChains.includes(network.name)) {
        const ethUsdAggregator = await deployments.get("MockV3Aggregator")
        ethUsdPriceFeedAddress = ethUsdAggregator.address
    } else {
        ethUsdPriceFeedAddress = networkConfig[chainId]["ethUsdPriceFeed"]
    }
    const args = [ethUsdPriceFeedAddress]
    const fundMe = await deploy("FundMe", {
        from: deployer,
        args: [ethUsdPriceFeedAddress],
        log: true,
        waitConfirmations: network.config.blockConfirmations || 1
    })
    if (
        !developmentChains.includes(network.name) &&
        process.env.ETHERSCAN_API_KEY
    ) {
        await verify(fundMe.address, args)
    }
}
module.exports.tags = ["all", "fundme"]
`

I am also attaching helper-hardhat-config.js file  code

`
const networkConfig = {
    31337: {
        name: "localhost",
    },
    // Price Feed Address, values can be obtained at https://docs.chain.link/docs/reference-contracts
    // Default one is ETH/USD contract on Kovan
    42: {
        name: "kovan",
        ethUsdPriceFeed: "0x9326BFA02ADD2366b30bacB125260Af641031331",
    },
    4: {
        name: "rinkeby",
        ethUsdPriceFeed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e",
    },
}

const developmentChains = ["hardhat", "localhost"]
const DECIMALS = "8"
const INITIAL_PRICE = "200000000000" // 2000

module.exports = {
    networkConfig,
    developmentChains,
    DECIMALS,
    INITIAL_PRICE
}
`

im also attaching hardhat.config.js file 

`
require("@nomiclabs/hardhat-waffle")
require("hardhat-gas-reporter")
require("@nomiclabs/hardhat-etherscan")
require("dotenv").config()
require("solidity-coverage")
require("hardhat-deploy")
// You need to export an object to set up your config
// Go to https://hardhat.org/config/ to learn more
/**
 * @type import('hardhat/config').HardhatUserConfig
 */

const COINMARKETCAP_API_KEY = process.env.COINMARKETCAP_API_KEY
const KOVAN_RPC_URL = process.env.KOVAN_RPC_URL
const RINKEBY_RPC_URL = process.env.RINKEBY_RPC_URL
const PRIVATE_KEY = process.env.PRIVATE_KEY
const ETHERSCAN_API_KEY = process.env.ETHERSCAN_API_KEY

module.exports = {
    defaultNetwork: "hardhat",
    networks: {
        hardhat: {
            chainId: 31337,
            // gasPrice: 130000000000,
        },
        kovan: {
            url: KOVAN_RPC_URL,
            accounts: [PRIVATE_KEY],
            chainId: 42,
            blockConfirmations: 6,
            gas: 6000000,
        },
        rinkeby: {
            url: RINKEBY_RPC_URL,
            accounts: [PRIVATE_KEY],
            chainId: 4,
            blockConfirmations: 6,
        },
    },
    solidity: {
        compilers: [
            {
                version: "0.8.8",
            },
            {
                version: "0.6.6",
            },
        ],
    },
    etherscan: {
        apiKey: ETHERSCAN_API_KEY,
    },
    gasReporter: {
        enabled: true,
        currency: "USD",
        outputFile: "gas-report.txt",
        noColors: true,
        // coinmarketcap: COINMARKETCAP_API_KEY,
    },
    namedAccounts: {
        deployer: {
            default: 0, // here this will by default take the first account as deployer
            1: 0, // similarly on mainnet it will take the first account as deployer. Note though that depending on how hardhat network are configured, the account 0 on one network can be different than on another
        },
    },
    mocha: {
        timeout: 500000,
    },
}
`


Please tell me where is problem im badly ctsuck i have checked code again and again
