### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by asmar10** [PatrickAlphaC/hardhat-fund-me-fcc#28]
Hi, im getting this error when i run "yarn hardhat deploy"

this is seems to be in the "00-deploy-mocks.js" file.

```
TypeError: Cannot read properties of undefined (reading 'length')
    at getFrom (C:\Users\ROSHAN\hardhat-fundme\node_modules\hardhat-deploy\src\helpers.ts:1713:14)  
    at _deploy (C:\Users\ROSHAN\hardhat-fundme\node_modules\hardhat-deploy\src\helpers.ts:533:9)    
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at _deployOne (C:\Users\ROSHAN\hardhat-fundme\node_modules\hardhat-deploy\src\helpers.ts:1004:16)
    at Object.deployFunc [as func] (C:\Users\ROSHAN\hardhat-fundme\deploy\00-deploy-mocks.js:15:9)  
    at DeploymentsManager.executeDeployScripts (C:\Users\ROSHAN\hardhat-fundme\node_modules\hardhat-deploy\src\DeploymentsManager.ts:1219:22)
    at DeploymentsManager.runDeploy (C:\Users\ROSHAN\hardhat-fundme\node_modules\hardhat-deploy\src\DeploymentsManager.ts:1052:5)
    at SimpleTaskDefinition.action (C:\Users\ROSHAN\hardhat-fundme\node_modules\hardhat-deploy\src\index.ts:438:5)
    at Environment._runTaskDefinition (C:\Users\ROSHAN\hardhat-fundme\node_modules\hardhat\src\internal\core\runtime-environment.ts:219:14)
    at Environment.run (C:\Users\ROSHAN\hardhat-fundme\node_modules\hardhat\src\internal\core\runtime-environment.ts:131:14)
    at DeploymentsManager.executeDeployScripts (C:\Users\ROSHAN\hardhat-fundme\node_modules\hardhat-deploy\src\DeploymentsManager.ts:1222:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at DeploymentsManager.runDeploy (C:\Users\ROSHAN\hardhat-fundme\node_modules\hardhat-deploy\src\DeploymentsManager.ts:1052:5)
    at SimpleTaskDefinition.action (C:\Users\ROSHAN\hardhat-fundme\node_modules\hardhat-deploy\src\index.ts:438:5)
    at Environment._runTaskDefinition (C:\Users\ROSHAN\hardhat-fundme\node_modules\hardhat\src\internal\core\runtime-environment.ts:219:14)
    at Environment.run (C:\Users\ROSHAN\hardhat-fundme\node_modules\hardhat\src\internal\core\runtime-environment.ts:131:14)
    at SimpleTaskDefinition.action (C:\Users\ROSHAN\hardhat-fundme\node_modules\hardhat-deploy\src\index.ts:584:32)
    at Environment._runTaskDefinition (C:\Users\ROSHAN\hardhat-fundme\node_modules\hardhat\src\internal\core\runtime-environment.ts:219:14)
    at Environment.run (C:\Users\ROSHAN\hardhat-fundme\node_modules\hardhat\src\internal\core\runtime-environment.ts:131:14)
    at SimpleTaskDefinition.action (C:\Users\ROSHAN\hardhat-fundme\node_modules\hardhat-deploy\src\index.ts:669:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Kindly help its been hours!

here's my code: 

```
const { network } = require("hardhat");
const { devChains, _INITIALANSWER, DECIMALS } = require("../hardhat-helper-config.js")


async function deployFunc(hre) {

    hre.getNamedAccounts;
    hre.deployments;

    const { deploy, log } = deployments;
    const { deployer } = await getNamedAccounts();

    if (devChains.includes(network.name)) {
        log("Deploying to development chain..")
        await deploy("MockV3Aggregator", {
            contract: "MockV3Aggregator",
            from: deployer,
            log: true,
            args: [DECIMALS, _INITIALANSWER],
        })
        console.log("Mock deployedd!!")
        console.log("----------------------")

    }
}


module.exports.default = deployFunc;
module.exports.tags = ["all", "mocks"]

```

PS: i have already added this in my hardhat-config.js file
```
 NamedAccounts: {
    deployer: {
      default: 0,
    },
  },```

**Comment by niraj2998** [comment]
I am not sure about this solution. But instead of this ` if (devChains.includes(network.name)) ` can you try this. For this don't for to import network at top `const { network } = require("hardhat")`
```
const chainId = network.config.chainId
if (chainId == 31337)
```

**Comment by asmar10** [comment]
still error

**Comment by asmar10** [comment]
Still the same :( i think ill just start from scratch again

**Comment by asmar10** [comment]
THIS WORKED!! THANKS ALOT <33


> > Still the same :( i think ill just start from scratch again
> 
> Try this in hardhat config:
> 
> ```
> namedAccounts: {
>         deployer: {
>             default: 0,
>         },
>         users: {
>             default: 0,
>         },
>     },
> ```

THIS WORKED!! THANKS ALOTT
