### ISSUE TITLE
Hardhat-fund-me-fcc ||| rinkeby/goerli deployment problem

### ISSUE THREAD

**Issue by rubysfuturellc** [PatrickAlphaC/hardhat-fund-me-fcc#31]
Lesson 7: Hardhat Fund Me
I am at roughly 10:58:49 / 1:07:54:30 in the video.

I am trying to deploy fundMe to Rinkeby (I have also tried Goerli) and I am getting the following error.

**Here is the error:**

Error: ERROR processing /Users/jabie/hardhat-fund-me-fcc/deploy/01-deploy-fund-me.js:
TypeError: Cannot read properties of undefined (reading 'ethUsdPriceFeed')
    at Object.module.exports [as func] (/Users/jabie/hardhat-fund-me-fcc/deploy/01-deploy-fund-me.js:36:56)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at DeploymentsManager.executeDeployScripts (/Users/jabie/hardhat-fund-me-fcc/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1219:22)
    at DeploymentsManager.runDeploy (/Users/jabie/hardhat-fund-me-fcc/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1052:5)
    at SimpleTaskDefinition.action (/Users/jabie/hardhat-fund-me-fcc/node_modules/hardhat-deploy/src/index.ts:438:5)
    at Environment._runTaskDefinition (/Users/jabie/hardhat-fund-me-fcc/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at Environment.run (/Users/jabie/hardhat-fund-me-fcc/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at SimpleTaskDefinition.action (/Users/jabie/hardhat-fund-me-fcc/node_modules/hardhat-deploy/src/index.ts:584:32)
    at Environment._runTaskDefinition (/Users/jabie/hardhat-fund-me-fcc/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at Environment.run (/Users/jabie/hardhat-fund-me-fcc/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at DeploymentsManager.executeDeployScripts (/Users/jabie/hardhat-fund-me-fcc/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1222:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at DeploymentsManager.runDeploy (/Users/jabie/hardhat-fund-me-fcc/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1052:5)
    at SimpleTaskDefinition.action (/Users/jabie/hardhat-fund-me-fcc/node_modules/hardhat-deploy/src/index.ts:438:5)
    at Environment._runTaskDefinition (/Users/jabie/hardhat-fund-me-fcc/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at Environment.run (/Users/jabie/hardhat-fund-me-fcc/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at SimpleTaskDefinition.action (/Users/jabie/hardhat-fund-me-fcc/node_modules/hardhat-deploy/src/index.ts:584:32)
    at Environment._runTaskDefinition (/Users/jabie/hardhat-fund-me-fcc/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at Environment.run (/Users/jabie/hardhat-fund-me-fcc/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at SimpleTaskDefinition.action (/Users/jabie/hardhat-fund-me-fcc/node_modules/hardhat-deploy/src/index.ts:669:5)
error Command failed with exit code 1.

Anyone else running into this or have an idea on what the issue is?

**Comment by PatrickAlphaC** [comment]
```
TypeError: Cannot read properties of undefined (reading 'ethUsdPriceFeed')
```

You're `ethUsdPriceFeed` is likely not being set correctly in the config or in the script. Closing for now. Check the config to see if there is an `ethUsdPriceFeed` entry for the chainId you're looking to deploy to.
