### ISSUE TITLE
Issues with fundme tag deploy

### ISSUE THREAD

**Issue by KevinDennyII** [PatrickAlphaC/hardhat-fund-me-fcc#82]
When I run the command `yarn hardhat deploy --tags fundme`, I am receiving an unexpected error

Here is the stack trace.
```
Error: ERROR processing /Users/ohhdennyservicesllc/Documents/workspace/hardhat-fund-me-fcc-js/deploy/01-deploy-fund-me.js:
Error: No deployment found for: MockV3Aggregator
    at Object.get (/Users/ohhdennyservicesllc/Documents/workspace/hardhat-fund-me-fcc-js/node_modules/hardhat-deploy/src/DeploymentsManager.ts:162:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.module.exports [as func] (/Users/ohhdennyservicesllc/Documents/workspace/hardhat-fund-me-fcc-js/deploy/01-deploy-fund-me.js:13:34)
    at DeploymentsManager.executeDeployScripts (/Users/ohhdennyservicesllc/Documents/workspace/hardhat-fund-me-fcc-js/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1220:22)
    at DeploymentsManager.runDeploy (/Users/ohhdennyservicesllc/Documents/workspace/hardhat-fund-me-fcc-js/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1053:5)
    at SimpleTaskDefinition.action (/Users/ohhdennyservicesllc/Documents/workspace/hardhat-fund-me-fcc-js/node_modules/hardhat-deploy/src/index.ts:409:5)
    at Environment._runTaskDefinition (/Users/ohhdennyservicesllc/Documents/workspace/hardhat-fund-me-fcc-js/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/Users/ohhdennyservicesllc/Documents/workspace/hardhat-fund-me-fcc-js/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at SimpleTaskDefinition.action (/Users/ohhdennyservicesllc/Documents/workspace/hardhat-fund-me-fcc-js/node_modules/hardhat-deploy/src/index.ts:555:32)
    at Environment._runTaskDefinition (/Users/ohhdennyservicesllc/Documents/workspace/hardhat-fund-me-fcc-js/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at DeploymentsManager.executeDeployScripts (/Users/ohhdennyservicesllc/Documents/workspace/hardhat-fund-me-fcc-js/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1223:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at DeploymentsManager.runDeploy (/Users/ohhdennyservicesllc/Documents/workspace/hardhat-fund-me-fcc-js/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1053:5)
    at SimpleTaskDefinition.action (/Users/ohhdennyservicesllc/Documents/workspace/hardhat-fund-me-fcc-js/node_modules/hardhat-deploy/src/index.ts:409:5)
    at Environment._runTaskDefinition (/Users/ohhdennyservicesllc/Documents/workspace/hardhat-fund-me-fcc-js/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/Users/ohhdennyservicesllc/Documents/workspace/hardhat-fund-me-fcc-js/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at SimpleTaskDefinition.action (/Users/ohhdennyservicesllc/Documents/workspace/hardhat-fund-me-fcc-js/node_modules/hardhat-deploy/src/index.ts:555:32)
    at Environment._runTaskDefinition (/Users/ohhdennyservicesllc/Documents/workspace/hardhat-fund-me-fcc-js/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/Users/ohhdennyservicesllc/Documents/workspace/hardhat-fund-me-fcc-js/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at SimpleTaskDefinition.action (/Users/ohhdennyservicesllc/Documents/workspace/hardhat-fund-me-fcc-js/node_modules/hardhat-deploy/src/index.ts:640:5)
error Command failed with exit code 1.
```

Any clues as to what might be happening here?

**Comment by RyanPaulGannon** [comment]
What happens when you run `yarn hardhat deploy`? I presume by adding the `--tags fundme` you aren't asking the mock to run first, hence the error `No deployment found for: MockV3Aggregator`?

**Comment by KevinDennyII** [comment]
> What happens when you run `yarn hardhat deploy`? I presume by adding the `--tags fundme` you aren't asking the mock to run first, hence the error `No deployment found for: MockV3Aggregator`?
> 
> Also my friend, I've just had a quick look through the closed issues (I've got an issue myself!) and your issue appears to have been closed. Give it a try and let us know.
> 
> #25

No issues with `yarn hardhat deploy`

how this came about when I was following along with the tutorial and Patrick explained the meaning of the tags and gave an example, so I followed through and got stuck.

It definitely all makes logical sense though.  Ill close this.

Thanks @RyanPaulGannon
